-- ==========================================
-- 1. 系统基础扩展与初始化
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";

-- 自动更新 updated_at 的触发器函数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ==========================================
-- 2. 用户系统模块 (Users & RBAC)
-- ==========================================

-- 用户基础表 (与 Supabase Auth 同步)
CREATE TABLE public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    avatar_url TEXT,
    bio TEXT, -- 个人简介
    catchphrase TEXT, -- 口头禅
    gender TEXT CHECK (gender IN ('male', 'female', 'secret')), -- 性别
    last_location GEOGRAPHY(POINT), -- 用户最后已知位置
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted')),
    registered_at TIMESTAMPTZ DEFAULT NOW(),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ -- 软删除支持
);

COMMENT ON TABLE public.users IS '用户基础信息表';
COMMENT ON COLUMN public.users.status IS '账户状态：active-正常, suspended-封禁, deleted-已注销';

-- 角色表
CREATE TABLE public.roles (
    id SERIAL PRIMARY KEY,
    role_name TEXT UNIQUE NOT NULL, -- e.g., 'admin', 'merchant', 'user'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 用户角色关联表
CREATE TABLE public.user_roles (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role_id INTEGER REFERENCES public.roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- ==========================================
-- 3. 商家模块 (Merchants)
-- ==========================================

-- 商家主表
CREATE TABLE public.merchants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT, -- 商家描述
    license_no TEXT UNIQUE, -- 营业执照号
    contact_name TEXT,
    phone TEXT, -- 联系电话 (原 contact_phone)
    address TEXT NOT NULL,
    location GEOGRAPHY(POINT), -- 经纬度坐标
    business_hours JSONB, -- 营业时间 e.g., {"open": "09:00", "close": "22:00"}
    category TEXT NOT NULL, -- 商家类型
    rating FLOAT DEFAULT 0,
    reviews_count INTEGER DEFAULT 0, -- 评价数量
    image_url TEXT, -- 商家封面图
    price TEXT, -- 人均消费
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'closed', 'rejected')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_merchants_location ON public.merchants USING GIST (location);
CREATE INDEX idx_merchants_category ON public.merchants(category);

-- 按距离搜索商家的 RPC 函数
CREATE OR REPLACE FUNCTION get_merchants_by_distance(user_lat FLOAT, user_lng FLOAT)
RETURNS TABLE (
    id BIGINT,
    name TEXT,
    description TEXT,
    address TEXT,
    category TEXT,
    phone TEXT,
    rating FLOAT,
    reviews_count INTEGER,
    image_url TEXT,
    price TEXT,
    status TEXT,
    dist_meters FLOAT
) 
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        m.id, m.name, m.description, m.address, m.category, m.phone, 
        m.rating, m.reviews_count, m.image_url, m.price, m.status,
        ST_Distance(m.location, ST_GeographyFromText('POINT(' || user_lng || ' ' || user_lat || ')')) AS dist_meters
    FROM public.merchants m
    WHERE m.status = 'active' AND m.deleted_at IS NULL
    ORDER BY dist_meters ASC;
END;
$$;

-- 商家认证审核表
CREATE TABLE public.merchant_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT REFERENCES public.merchants(id) ON DELETE CASCADE,
    verifier_id UUID REFERENCES public.users(id),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    audit_remark TEXT, -- 审核备注
    evidence_urls TEXT[], -- 证照图片URLs
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 商家管理员关联表 (支持多用户管理同一商家)
CREATE TABLE public.merchant_users (
    merchant_id BIGINT REFERENCES public.merchants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    is_owner BOOLEAN DEFAULT false,
    PRIMARY KEY (merchant_id, user_id)
);

-- ==========================================
-- 4. 评价系统模块 (Reviews)
-- ==========================================

-- 评价主表
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) NOT NULL,
    merchant_id BIGINT REFERENCES public.merchants(id) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content TEXT,
    image_urls TEXT[],
    useful_count INTEGER DEFAULT 0,
    report_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_reviews_merchant ON public.reviews(merchant_id);
CREATE INDEX idx_reviews_user ON public.reviews(user_id);

-- 收藏关联表
CREATE TABLE public.favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    merchant_id BIGINT REFERENCES public.merchants(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, merchant_id)
);

-- 评价回复表
CREATE TABLE public.review_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT REFERENCES public.reviews(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 评价标签表
CREATE TABLE public.review_tags (
    id SERIAL PRIMARY KEY,
    tag_name TEXT UNIQUE NOT NULL,
    category TEXT, -- 标签分类：口味、服务、环境等
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 评价与标签关联表
CREATE TABLE public.review_tag_refs (
    review_id BIGINT REFERENCES public.reviews(id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES public.review_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (review_id, tag_id)
);

-- ==========================================
-- 5. 系统基础模块 (System)
-- ==========================================

-- 系统配置表
CREATE TABLE public.system_configs (
    id SERIAL PRIMARY KEY,
    config_key TEXT UNIQUE NOT NULL,
    config_value TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 操作日志表
CREATE TABLE public.operation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id),
    action TEXT NOT NULL, -- 操作类型
    target_table TEXT,
    target_id TEXT,
    detail JSONB,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 数据字典表
CREATE TABLE public.data_dictionaries (
    id SERIAL PRIMARY KEY,
    dict_code TEXT NOT NULL, -- 字典编码
    dict_label TEXT NOT NULL, -- 字典项名称
    dict_value TEXT NOT NULL, -- 字典项值
    sort_order INTEGER DEFAULT 0,
    is_system BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (dict_code, dict_value)
);

-- ==========================================
-- 6. 触发器与自动维护逻辑
-- ==========================================

-- 为所有包含 updated_at 的表添加触发器
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN (SELECT table_name FROM information_schema.columns WHERE column_name = 'updated_at' AND table_schema = 'public') LOOP
        EXECUTE format('CREATE TRIGGER trigger_update_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();', t);
    END LOOP;
END $$;

-- 用户同步触发器 (从 auth.users 自动同步到 public.users)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, username, email, avatar_url)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'username', NEW.email),
        NEW.email,
        NEW.raw_user_meta_data->>'avatar_url'
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 先删除同名触发器以支持重复运行
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================
-- 7. 视图与查询优化
-- ==========================================

-- 商家详细信息视图 (包含评分统计)
CREATE VIEW public.view_merchant_details AS
SELECT 
    m.*,
    COUNT(r.id) as total_reviews,
    COALESCE(AVG(r.rating), 0) as calculated_avg_rating
FROM public.merchants m
LEFT JOIN public.reviews r ON m.id = r.merchant_id AND r.deleted_at IS NULL
WHERE m.deleted_at IS NULL
GROUP BY m.id;

-- ==========================================
-- 8. 安全策略 (RLS)
-- ==========================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

ALTER TABLE public.merchants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view active merchants" ON public.merchants FOR SELECT USING (status = 'active' AND deleted_at IS NULL);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view reviews" ON public.reviews FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Authenticated users can insert reviews" ON public.reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can update their own reviews" ON public.reviews FOR UPDATE USING (auth.uid() = user_id);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own favorites" ON public.favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can add favorites" ON public.favorites FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can delete their own favorites" ON public.favorites FOR DELETE USING (auth.uid() = user_id);
